/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccentCard: typeof import('./components/common/AccentCard.vue')['default']
    AiChatPanel: typeof import('./components/ai-studio/AiChatPanel.vue')['default']
    AiForecastPanel: typeof import('./components/ai-studio/AiForecastPanel.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    EntityForm: typeof import('./components/dataCenter/EntityForm.vue')['default']
    EntityList: typeof import('./components/dataCenter/EntityList.vue')['default']
    FloatingAiChat: typeof import('./components/common/FloatingAiChat.vue')['default']
    HighCostTable: typeof import('./components/operations/HighCostTable.vue')['default']
    InventoryAlertTable: typeof import('./components/overview/InventoryAlertTable.vue')['default']
    InventoryPriorityTable: typeof import('./components/operations/InventoryPriorityTable.vue')['default']
    LogisticsAlertTable: typeof import('./components/operations/LogisticsAlertTable.vue')['default']
    MetricCard: typeof import('./components/common/MetricCard.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    RecentOrderTable: typeof import('./components/overview/RecentOrderTable.vue')['default']
    RiskDistChart: typeof import('./components/overview/RiskDistChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendChart: typeof import('./components/overview/SalesTrendChart.vue')['default']
    ServiceStatus: typeof import('./components/common/ServiceStatus.vue')['default']
    SupplierRankTable: typeof import('./components/operations/SupplierRankTable.vue')['default']
    TopSupplierTable: typeof import('./components/overview/TopSupplierTable.vue')['default']
  }
}
