export const entityOptions = [
  { key: 'orders', label: '订单' },
  { key: 'inventory', label: '库存' },
  { key: 'suppliers', label: '供应商' },
  { key: 'logistics', label: '物流' },
  { key: 'costs', label: '成本' },
  { key: 'risks', label: '风险' },
]

export const entityForms = {
  orders: [
    { key: 'date', label: '订单日期', type: 'date' },
    { key: 'customer_region', label: '客户区域', placeholder: '如：华东' },
    { key: 'product_id', label: '产品编号', placeholder: '如：P006' },
    { key: 'product_name', label: '产品名称', placeholder: '如：核心零件 F' },
    { key: 'quantity', label: '数量', type: 'number' },
    { key: 'unit_price', label: '单价', type: 'number' },
    { key: 'status', label: '状态', placeholder: 'pending / completed' },
  ],
  inventory: [
    { key: 'product_id', label: '产品编号', placeholder: '如：P006' },
    { key: 'product_name', label: '产品名称', placeholder: '如：核心零件 F' },
    { key: 'warehouse_id', label: '仓库编号', placeholder: '如：W004' },
    { key: 'warehouse_name', label: '仓库名称', placeholder: '如：武汉中心仓' },
    { key: 'current_stock', label: '当前库存', type: 'number' },
    { key: 'safety_stock', label: '安全库存', type: 'number' },
    { key: 'max_stock', label: '最大库存', type: 'number' },
    { key: 'unit_cost', label: '单位成本', type: 'number' },
  ],
  suppliers: [
    { key: 'supplier_name', label: '供应商名称', placeholder: '如：华中精工' },
    { key: 'region', label: '区域', placeholder: '如：湖北' },
    { key: 'on_time_rate', label: '准时交付率', type: 'number', placeholder: '输入 0.92 或 92' },
    { key: 'quality_rate', label: '质量合格率', type: 'number', placeholder: '输入 0.95 或 95' },
    { key: 'price_stability', label: '价格稳定性', type: 'number', placeholder: '输入 0.90 或 90' },
    { key: 'response_score', label: '响应评分', type: 'number', placeholder: '输入 0.88 或 88' },
    { key: 'cooperation_years', label: '合作年限', type: 'number' },
  ],
  logistics: [
    { key: 'order_id', label: '关联订单号', placeholder: '如：O20260501001' },
    { key: 'origin', label: '起点', placeholder: '如：广州' },
    { key: 'destination', label: '终点', placeholder: '如：成都' },
    { key: 'carrier', label: '承运商', placeholder: '如：顺达物流' },
    { key: 'expected_duration_hours', label: '预计时长（小时）', type: 'number' },
    { key: 'actual_duration_hours', label: '实际时长（小时）', type: 'number' },
    { key: 'status', label: '状态', placeholder: 'on_time / delayed' },
    { key: 'transport_cost', label: '运输成本', type: 'number' },
  ],
  costs: [
    { key: 'date', label: '日期', type: 'date' },
    { key: 'product_id', label: '产品编号', placeholder: '如：P006' },
    { key: 'purchase_cost', label: '采购成本', type: 'number' },
    { key: 'storage_cost', label: '仓储成本', type: 'number' },
    { key: 'transport_cost', label: '运输成本', type: 'number' },
    { key: 'return_cost', label: '退货成本', type: 'number' },
  ],
  risks: [
    { key: 'risk_type', label: '风险类型', placeholder: '如：库存不足' },
    { key: 'risk_level', label: '风险等级', placeholder: 'Critical / High / Medium / Low' },
    { key: 'related_object', label: '关联对象', placeholder: '如：P006' },
    { key: 'description', label: '风险描述', as: 'textarea', placeholder: '描述风险现象与背景' },
    { key: 'suggestion', label: '处理建议', as: 'textarea', placeholder: '如：增加安全库存并切换备选供应商' },
    { key: 'status', label: '状态', placeholder: 'open / resolved' },
  ],
}
